# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agentanycast/v1/agent_card.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n agentanycast/v1/agent_card.proto\x12\x0f\x61gentanycast.v1\"\xb7\x01\n\tAgentCard\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x18\n\x10protocol_version\x18\x04 \x01(\t\x12&\n\x06skills\x18\x05 \x03(\x0b\x32\x16.agentanycast.v1.Skill\x12\x34\n\rp2p_extension\x18\n \x01(\x0b\x32\x1d.agentanycast.v1.P2PExtension\"U\n\x05Skill\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cinput_schema\x18\x03 \x01(\t\x12\x15\n\routput_schema\x18\x04 \x01(\t\"V\n\x0cP2PExtension\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x1c\n\x14supported_transports\x18\x02 \x03(\t\x12\x17\n\x0frelay_addresses\x18\x03 \x03(\tBRZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentanycast.v1.agent_card_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1'
  _AGENTCARD._serialized_start=54
  _AGENTCARD._serialized_end=237
  _SKILL._serialized_start=239
  _SKILL._serialized_end=324
  _P2PEXTENSION._serialized_start=326
  _P2PEXTENSION._serialized_end=412
# @@protoc_insertion_point(module_scope)
