# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agentanycast/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61gentanycast/v1/common.proto\x12\x0f\x61gentanycast.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n\x08PeerInfo\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x11\n\taddresses\x18\x02 \x03(\t\x12\x38\n\x0f\x63onnection_type\x18\x03 \x01(\x0e\x32\x1f.agentanycast.v1.ConnectionType\x12\x30\n\x0c\x63onnected_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xbb\x01\n\x08NodeInfo\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x18\n\x10listen_addresses\x18\x02 \x03(\t\x12*\n\x08nat_type\x18\x03 \x01(\x0e\x32\x18.agentanycast.v1.NATType\x12\x17\n\x0f\x63onnected_peers\x18\x04 \x01(\x05\x12.\n\nstarted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07version\x18\x06 \x01(\t\"\x9b\x01\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12<\n\x08metadata\x18\x03 \x03(\x0b\x32*.agentanycast.v1.ErrorDetail.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*h\n\x0e\x43onnectionType\x12\x1f\n\x1b\x43ONNECTION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43ONNECTION_TYPE_DIRECT\x10\x01\x12\x19\n\x15\x43ONNECTION_TYPE_RELAY\x10\x02*N\n\x07NATType\x12\x18\n\x14NAT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fNAT_TYPE_PUBLIC\x10\x01\x12\x14\n\x10NAT_TYPE_PRIVATE\x10\x02\x42RZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentanycast.v1.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZPgithub.com/agentanycast/agentanycast-proto/gen/go/agentanycast/v1;agentanycastv1'
  _ERRORDETAIL_METADATAENTRY._options = None
  _ERRORDETAIL_METADATAENTRY._serialized_options = b'8\001'
  _CONNECTIONTYPE._serialized_start=587
  _CONNECTIONTYPE._serialized_end=691
  _NATTYPE._serialized_start=693
  _NATTYPE._serialized_end=771
  _PEERINFO._serialized_start=83
  _PEERINFO._serialized_end=237
  _NODEINFO._serialized_start=240
  _NODEINFO._serialized_end=427
  _ERRORDETAIL._serialized_start=430
  _ERRORDETAIL._serialized_end=585
  _ERRORDETAIL_METADATAENTRY._serialized_start=538
  _ERRORDETAIL_METADATAENTRY._serialized_end=585
# @@protoc_insertion_point(module_scope)
